jobs:
  - name : vjob1-manifest
    type : manifest
    steps :
      - GET resourcev-image
      - GET resourcev-dockeroption
      - GET resourcev-ecsparam
      
  #- name: vjob2-ecsdeploy
 #   type: ecsDeploy
#    steps:
     # - GET vjob1-manifest
    #  - GET resourcev-ecscluster
