jobs:
  - name : e2eplv2jobv-manifest
    type : manifest
    steps :
      - GET: e2eplv2v-image
      - GET: e2eplv2v-dockeroption
      - GET: e2eplv2v-ecsparam
      - GET: e2eplv2v-replica
      
  #- name: e2eplv2jobv-ecsdeploy
 #   type: ecsDeploy
#    steps:
     # - GET: e2eplv2jobv-manifest
    #  - GET: e2eplv2v-ecscluster
